name       : opencl-headers
version    : 2020.12.18
release    : 2
source     :
    - https://github.com/KhronosGroup/OpenCL-Headers/archive/refs/tags/v2020.12.18.tar.gz : 5dad6d436c0d7646ef62a39ef6cd1f3eba0a98fc9157808dfc1d808f3705ebc2
license    : Apache-2.0
component  : programming.devel
homepage   : https://github.com/KhronosGroup/OpenCL-Headers/
summary    : OpenCL C header files
description: |
    OpenCL (Open Computing Language) header files for the C programming language.
patterns   :
    - /usr/include/CL/*
install    : |
    # Get rid of Direct3D stuffs
    rm -vf CL/{cl_d3d,cl_dx9}*.h

    install -Dm00644 CL/*.h -t $installdir/usr/include/CL
