name       : opencl-headers
version    : 2023.04.17
release    : 4
source     :
    - https://github.com/KhronosGroup/OpenCL-Headers/archive/refs/tags/v2023.04.17.tar.gz : 0ce992f4167f958f68a37918dec6325be18f848dee29a4521c633aae3304915d
license    : Apache-2.0
component  : programming.devel
homepage   : https://github.com/KhronosGroup/OpenCL-Headers/
summary    : OpenCL C header files
description: |
    OpenCL (Open Computing Language) header files for the C programming language.
patterns   :
    - /usr/include/CL/*
install    : |
    # Get rid of Direct3D stuffs
    rm -vf CL/{cl_d3d,cl_dx9}*.h

    install -Dm00644 CL/*.h -t $installdir/usr/include/CL
