name       : opencl-headers
version    : 2.2
release    : 1
source     :
    - git|https://github.com/KhronosGroup/OpenCL-Headers : f039db6764d52388658ef15c30b2237bbda49803
    - https://github.com/KhronosGroup/OpenCL-CLHPP/archive/v2.0.10.tar.gz : fa27456295c3fa534ce824eb0314190a8b3ebd3ba4d93a0b1270fc65bf378f2b
license    : MIT
component  : programming
summary    : OpenCL (Open Computing Language) header files
description: |
    OpenCL (Open Computing Language) header files
patterns   :
 - /*
setup      : |
    # Get rid of Direct3D stuffs
    rm -vf opencl22/CL/{cl_d3d,cl_dx9}*.h

    tar xf $sources/v2.0.10.tar.gz
build      : |
    cd OpenCL-CLHPP-*

    python gen_cl_hpp.py -i input_cl.hpp -o cl.hpp
    mv input_cl2.hpp cl2.hpp
install    : |
    install -D -m00644 opencl22/CL/*.h -t $installdir/usr/include/CL

    cd OpenCL-CLHPP-*
    install -m00644 cl{,2}.hpp -t $installdir/usr/include/CL

